//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace themenava.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class message
    {
        public int id { get; set; }
        [Required ]
        public string name { get; set; }
        [Required]
        public string email { get; set; }
        [Required]
        public string sms { get; set; }
        [Required]
        public string phone_no { get; set; }
        public string congratulate_message { get; set; }
    }
}
