//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace themenava.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class assainmentEntities6 : DbContext
    {
        public assainmentEntities6()
            : base("name=assainmentEntities6")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<admin_login> admin_login { get; set; }
        public DbSet<hotel> hotels { get; set; }
        public DbSet<message> messages { get; set; }
        public DbSet<order> orders { get; set; }
        public DbSet<orders_complete> orders_complete { get; set; }
        public DbSet<orders_inpregress> orders_inpregress { get; set; }
        public DbSet<place> places { get; set; }
        public DbSet<recycle_bin> recycle_bin { get; set; }
    }
}
